[[languages.cpp.environments]]
CXX = "g++-12"
CXXFLAGS = [
    "-std=gnu++20",
    "-Wno-misleading-indentation",
    "-Wall",
    "-Wextra",
    "-fconcepts-diagnostics-depth=5",
    "-Wno-char-subscripts",
    "-O2",
    "-I", 
    "/opt/ac-library",
    "-I",
    "/opt/boost/gcc/include",
    "-L",
    "/opt/boost/gcc/lib",
    "-lgmpxx",
    "-lgmp",
    "-I",
    "/usr/include/eigen"
]



